CREATE TABLE Bugs (
	BID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BGID uniqueidentifier NOT NULL,
	BUID INT NOT NULL,
	BAUIDS nvarchar(max) NULL,
	CDate DATETIME2 NOT NULL,
	CTitle nvarchar(200) NOT NULL,
	CText nvarchar(4000) NOT NULL
)