CREATE TABLE Bugs (
	BID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BGID uniqueidentifier NOT NULL,
	BUID INT NOT NULL,
	BAUIDS nvarchar(max) NULL,
	BDate DATETIME2 NOT NULL,
	BTitle nvarchar(200) NOT NULL,
	BText nvarchar(4000) NOT NULL,
	BStatus INT NOT NULL,
)