CREATE TABLE TasksNotes (
	TNID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TNGID uniqueidentifier NOT NULL,
	TNTGID uniqueidentifier NOT NULL,
	TNUID INT NOT NULL,
	TNNote nvarchar(2000) NOT NULL,
	TNDate DATETIME2 NOT NULL,
	TNEditDate DATETIME2 NULL,
)