name: OrganiserCI
on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: Organiser.Core
      - name: Build
        run: dotnet build --no-restore
        working-directory: Organiser.Core
      - name: Test
        run: dotnet test
        working-directory: Organiser.Core
